import type { LvglWidgetDefinition, LvglWidgetType } from './lvgl';

export const WIDGET_DEFINITIONS: Record<LvglWidgetType, LvglWidgetDefinition> = {
  lv_obj: {
    type: 'lv_obj',
    label: 'Base Object',
    icon: '□',
    defaultSize: { w: 100, h: 100 },
    canHaveChildren: true,
    properties: [
      { key: 'id', label: 'ID', type: 'text', default: '', category: 'basic' },
      { key: 'hidden', label: 'Hidden', type: 'boolean', default: false, category: 'basic' },
      { key: 'clickable', label: 'Clickable', type: 'boolean', default: true, category: 'basic' },
      { key: 'scrollable', label: 'Scrollable', type: 'boolean', default: true, category: 'basic' },
    ],
  },
  lv_btn: {
    type: 'lv_btn',
    label: 'Button',
    icon: '⬜',
    defaultSize: { w: 120, h: 50 },
    canHaveChildren: true,
    properties: [
      { key: 'id', label: 'ID', type: 'text', default: '', category: 'basic' },
      { key: 'text', label: 'Text', type: 'text', default: 'Button', category: 'basic' },
      { key: 'checkable', label: 'Checkable', type: 'boolean', default: false, category: 'specific' },
      { key: 'checked', label: 'Checked', type: 'boolean', default: false, category: 'specific' },
    ],
  },
  lv_label: {
    type: 'lv_label',
    label: 'Label',
    icon: 'A',
    defaultSize: { w: 100, h: 20 },
    canHaveChildren: false,
    properties: [
      { key: 'id', label: 'ID', type: 'text', default: '', category: 'basic' },
      { key: 'text', label: 'Text', type: 'textarea', default: 'Label', category: 'basic' },
      { key: 'longMode', label: 'Long Mode', type: 'select', default: 'wrap', options: [
        { label: 'Wrap', value: 'LV_LABEL_LONG_WRAP' },
        { label: 'Dot', value: 'LV_LABEL_LONG_DOT' },
        { label: 'Scroll', value: 'LV_LABEL_LONG_SCROLL' },
        { label: 'Scroll Circular', value: 'LV_LABEL_LONG_SCROLL_CIRCULAR' },
        { label: 'Clip', value: 'LV_LABEL_LONG_CLIP' },
      ], category: 'specific' },
      { key: 'recolor', label: 'Recolor', type: 'boolean', default: false, category: 'specific' },
    ],
  },
  lv_slider: {
    type: 'lv_slider',
    label: 'Slider',
    icon: '—',
    defaultSize: { w: 200, h: 20 },
    canHaveChildren: false,
    properties: [
      { key: 'id', label: 'ID', type: 'text', default: '', category: 'basic' },
      { key: 'min', label: 'Min Value', type: 'number', default: 0, category: 'specific' },
      { key: 'max', label: 'Max Value', type: 'number', default: 100, category: 'specific' },
      { key: 'value', label: 'Value', type: 'number', default: 50, category: 'specific' },
      { key: 'mode', label: 'Mode', type: 'select', default: 'normal', options: [
        { label: 'Normal', value: 'LV_SLIDER_MODE_NORMAL' },
        { label: 'Symmetric', value: 'LV_SLIDER_MODE_SYMMETRICAL' },
        { label: 'Range', value: 'LV_SLIDER_MODE_RANGE' },
      ], category: 'specific' },
    ],
  },
  lv_bar: {
    type: 'lv_bar',
    label: 'Bar',
    icon: '▬',
    defaultSize: { w: 200, h: 30 },
    canHaveChildren: false,
    properties: [
      { key: 'id', label: 'ID', type: 'text', default: '', category: 'basic' },
      { key: 'min', label: 'Min Value', type: 'number', default: 0, category: 'specific' },
      { key: 'max', label: 'Max Value', type: 'number', default: 100, category: 'specific' },
      { key: 'value', label: 'Value', type: 'number', default: 50, category: 'specific' },
      { key: 'rangeMode', label: 'Range Mode', type: 'boolean', default: false, category: 'specific' },
      { key: 'animDuration', label: 'Anim Duration (ms)', type: 'number', default: 0, category: 'specific' },
    ],
  },
  lv_arc: {
    type: 'lv_arc',
    label: 'Arc',
    icon: '◡',
    defaultSize: { w: 150, h: 150 },
    canHaveChildren: false,
    properties: [
      { key: 'id', label: 'ID', type: 'text', default: '', category: 'basic' },
      { key: 'min', label: 'Min Value', type: 'number', default: 0, category: 'specific' },
      { key: 'max', label: 'Max Value', type: 'number', default: 100, category: 'specific' },
      { key: 'value', label: 'Value', type: 'number', default: 50, category: 'specific' },
      { key: 'startAngle', label: 'Start Angle', type: 'number', default: 135, category: 'specific' },
      { key: 'endAngle', label: 'End Angle', type: 'number', default: 270, category: 'specific' },
      { key: 'rotation', label: 'Rotation', type: 'number', default: 0, category: 'specific' },
      { key: 'type', label: 'Type', type: 'select', default: 'normal', options: [
        { label: 'Normal', value: 'LV_ARC_MODE_NORMAL' },
        { label: 'Reverse', value: 'LV_ARC_MODE_REVERSE' },
        { label: 'Symmetric', value: 'LV_ARC_MODE_SYMMETRICAL' },
      ], category: 'specific' },
      { key: 'bgArcOpacity', label: 'BG Arc Opacity', type: 'number', default: 255, min: 0, max: 255, category: 'specific' },
      { key: 'rounded', label: 'Rounded Ends', type: 'boolean', default: true, category: 'specific' },
      { key: 'changeRate', label: 'Change Rate', type: 'number', default: 720, category: 'specific' },
    ],
  },
  lv_led: {
    type: 'lv_led',
    label: 'LED',
    icon: '●',
    defaultSize: { w: 40, h: 40 },
    canHaveChildren: false,
    properties: [
      { key: 'id', label: 'ID', type: 'text', default: '', category: 'basic' },
      { key: 'brightness', label: 'Brightness', type: 'number', default: 255, min: 0, max: 255, category: 'specific' },
      { key: 'onColor', label: 'On Color', type: 'color', default: '#ff0000', category: 'specific' },
      { key: 'offColor', label: 'Off Color', type: 'color', default: '#ff000033', category: 'specific' },
    ],
  },
  lv_switch: {
    type: 'lv_switch',
    label: 'Switch',
    icon: '⏤',
    defaultSize: { w: 60, h: 30 },
    canHaveChildren: false,
    properties: [
      { key: 'id', label: 'ID', type: 'text', default: '', category: 'basic' },
      { key: 'checked', label: 'Checked', type: 'boolean', default: false, category: 'specific' },
    ],
  },
  lv_checkbox: {
    type: 'lv_checkbox',
    label: 'Checkbox',
    icon: '☑',
    defaultSize: { w: 120, h: 30 },
    canHaveChildren: false,
    properties: [
      { key: 'id', label: 'ID', type: 'text', default: '', category: 'basic' },
      { key: 'text', label: 'Text', type: 'text', default: 'Checkbox', category: 'basic' },
      { key: 'checked', label: 'Checked', type: 'boolean', default: false, category: 'specific' },
      { key: 'disabled', label: 'Disabled', type: 'boolean', default: false, category: 'specific' },
    ],
  },
  lv_dropdown: {
    type: 'lv_dropdown',
    label: 'Dropdown',
    icon: '▾',
    defaultSize: { w: 150, h: 40 },
    canHaveChildren: false,
    properties: [
      { key: 'id', label: 'ID', type: 'text', default: '', category: 'basic' },
      { key: 'options', label: 'Options (newline separated)', type: 'textarea', default: 'Option 1\nOption 2\nOption 3', category: 'specific' },
      { key: 'selected', label: 'Selected Index', type: 'number', default: 0, category: 'specific' },
      { key: 'showSelected', label: 'Show Selected', type: 'boolean', default: true, category: 'specific' },
      { key: 'dir', label: 'List Direction', type: 'select', default: 'down', options: [
        { label: 'Down', value: 'LV_DIR_DOWN' },
        { label: 'Up', value: 'LV_DIR_UP' },
        { label: 'Left', value: 'LV_DIR_LEFT' },
        { label: 'Right', value: 'LV_DIR_RIGHT' },
      ], category: 'specific' },
      { key: 'maxHeight', label: 'Max List Height', type: 'number', default: 200, category: 'specific' },
    ],
  },
  lv_textarea: {
    type: 'lv_textarea',
    label: 'Text Area',
    icon: '⌨',
    defaultSize: { w: 250, h: 100 },
    canHaveChildren: false,
    properties: [
      { key: 'id', label: 'ID', type: 'text', default: '', category: 'basic' },
      { key: 'text', label: 'Text', type: 'textarea', default: '', category: 'basic' },
      { key: 'placeholder', label: 'Placeholder', type: 'text', default: 'Enter text...', category: 'specific' },
      { key: 'maxLength', label: 'Max Length', type: 'number', default: 0, category: 'specific' },
      { key: 'passwordMode', label: 'Password Mode', type: 'boolean', default: false, category: 'specific' },
      { key: 'oneLine', label: 'One Line', type: 'boolean', default: false, category: 'specific' },
      { key: 'acceptedChars', label: 'Accepted Chars', type: 'text', default: '', category: 'specific' },
      { key: 'cursorPos', label: 'Cursor Position', type: 'number', default: 0, category: 'specific' },
    ],
  },
  lv_img: {
    type: 'lv_img',
    label: 'Image',
    icon: '🖼',
    defaultSize: { w: 100, h: 100 },
    canHaveChildren: false,
    properties: [
      { key: 'id', label: 'ID', type: 'text', default: '', category: 'basic' },
      { key: 'src', label: 'Source', type: 'text', default: '', category: 'specific' },
      { key: 'offsetX', label: 'Offset X', type: 'number', default: 0, category: 'specific' },
      { key: 'offsetY', label: 'Offset Y', type: 'number', default: 0, category: 'specific' },
      { key: 'angle', label: 'Angle', type: 'number', default: 0, category: 'specific' },
      { key: 'zoom', label: 'Zoom', type: 'number', default: 256, min: 1, max: 512, category: 'specific' },
      { key: 'antialias', label: 'Antialias', type: 'boolean', default: true, category: 'specific' },
      { key: 'autoSize', label: 'Auto Size', type: 'boolean', default: true, category: 'specific' },
    ],
  },
  lv_imgbtn: {
    type: 'lv_imgbtn',
    label: 'Image Button',
    icon: '🖼',
    defaultSize: { w: 100, h: 60 },
    canHaveChildren: false,
    properties: [
      { key: 'id', label: 'ID', type: 'text', default: '', category: 'basic' },
      { key: 'srcReleased', label: 'Released Image', type: 'text', default: '', category: 'specific' },
      { key: 'srcPressed', label: 'Pressed Image', type: 'text', default: '', category: 'specific' },
      { key: 'srcDisabled', label: 'Disabled Image', type: 'text', default: '', category: 'specific' },
      { key: 'srcChecked', label: 'Checked Image', type: 'text', default: '', category: 'specific' },
      { key: 'checkable', label: 'Checkable', type: 'boolean', default: false, category: 'specific' },
    ],
  },
  lv_btnmatrix: {
    type: 'lv_btnmatrix',
    label: 'Button Matrix',
    icon: '⊞',
    defaultSize: { w: 300, h: 150 },
    canHaveChildren: false,
    properties: [
      { key: 'id', label: 'ID', type: 'text', default: '', category: 'basic' },
      { key: 'map', label: 'Button Map (comma separated)', type: 'textarea', default: '1,2,3\n4,5,6\n7,8,9', category: 'specific' },
      { key: 'colCount', label: 'Column Count', type: 'number', default: 3, category: 'specific' },
      { key: 'oneChecked', label: 'One Checked', type: 'boolean', default: false, category: 'specific' },
    ],
  },
  lv_chart: {
    type: 'lv_chart',
    label: 'Chart',
    icon: '📊',
    defaultSize: { w: 300, h: 200 },
    canHaveChildren: false,
    properties: [
      { key: 'id', label: 'ID', type: 'text', default: '', category: 'basic' },
      { key: 'type', label: 'Chart Type', type: 'select', default: 'line', options: [
        { label: 'Line', value: 'LV_CHART_TYPE_LINE' },
        { label: 'Bar', value: 'LV_CHART_TYPE_BAR' },
        { label: 'Scatter', value: 'LV_CHART_TYPE_SCATTER' },
        { label: 'None', value: 'LV_CHART_TYPE_NONE' },
      ], category: 'specific' },
      { key: 'rangeMin', label: 'Range Min', type: 'number', default: 0, category: 'specific' },
      { key: 'rangeMax', label: 'Range Max', type: 'number', default: 100, category: 'specific' },
      { key: 'pointCount', label: 'Point Count', type: 'number', default: 10, category: 'specific' },
      { key: 'serieCount', label: 'Serie Count', type: 'number', default: 1, category: 'specific' },
      { key: 'axisTicks', label: 'Show Axis Ticks', type: 'boolean', default: true, category: 'specific' },
      { key: 'divLineX', label: 'Div Line X', type: 'boolean', default: true, category: 'specific' },
      { key: 'divLineY', label: 'Div Line Y', type: 'boolean', default: true, category: 'specific' },
      { key: 'updateMode', label: 'Update Mode', type: 'select', default: 'circular', options: [
        { label: 'Circular', value: 'LV_CHART_UPDATE_MODE_CIRCULAR' },
        { label: 'Shift', value: 'LV_CHART_UPDATE_MODE_SHIFT' },
      ], category: 'specific' },
    ],
  },
  lv_table: {
    type: 'lv_table',
    label: 'Table',
    icon: '⊟',
    defaultSize: { w: 300, h: 200 },
    canHaveChildren: false,
    properties: [
      { key: 'id', label: 'ID', type: 'text', default: '', category: 'basic' },
      { key: 'colCount', label: 'Column Count', type: 'number', default: 3, category: 'specific' },
      { key: 'rowCount', label: 'Row Count', type: 'number', default: 3, category: 'specific' },
      { key: 'colWidths', label: 'Column Widths (comma)', type: 'text', default: '80,80,80', category: 'specific' },
    ],
  },
  lv_tabview: {
    type: 'lv_tabview',
    label: 'Tab View',
    icon: '📑',
    defaultSize: { w: 300, h: 200 },
    canHaveChildren: true,
    properties: [
      { key: 'id', label: 'ID', type: 'text', default: '', category: 'basic' },
      { key: 'tabCount', label: 'Tab Count', type: 'number', default: 3, category: 'specific' },
      { key: 'tabNames', label: 'Tab Names (comma)', type: 'text', default: 'Tab1,Tab2,Tab3', category: 'specific' },
      { key: 'activeTab', label: 'Active Tab', type: 'number', default: 0, category: 'specific' },
      { key: 'tabPos', label: 'Tab Position', type: 'select', default: 'top', options: [
        { label: 'Top', value: 'LV_DIR_TOP' },
        { label: 'Bottom', value: 'LV_DIR_BOTTOM' },
        { label: 'Left', value: 'LV_DIR_LEFT' },
        { label: 'Right', value: 'LV_DIR_RIGHT' },
      ], category: 'specific' },
    ],
  },
  lv_win: {
    type: 'lv_win',
    label: 'Window',
    icon: '🗗',
    defaultSize: { w: 300, h: 200 },
    canHaveChildren: true,
    properties: [
      { key: 'id', label: 'ID', type: 'text', default: '', category: 'basic' },
      { key: 'title', label: 'Title', type: 'text', default: 'Window', category: 'basic' },
      { key: 'showClose', label: 'Show Close Btn', type: 'boolean', default: true, category: 'specific' },
      { key: 'showHeader', label: 'Show Header', type: 'boolean', default: true, category: 'specific' },
    ],
  },
  lv_msgbox: {
    type: 'lv_msgbox',
    label: 'Message Box',
    icon: '💬',
    defaultSize: { w: 250, h: 150 },
    canHaveChildren: false,
    properties: [
      { key: 'id', label: 'ID', type: 'text', default: '', category: 'basic' },
      { key: 'title', label: 'Title', type: 'text', default: 'Message', category: 'basic' },
      { key: 'text', label: 'Text', type: 'textarea', default: 'Message body', category: 'basic' },
      { key: 'buttons', label: 'Buttons (comma)', type: 'text', default: 'OK,Cancel', category: 'specific' },
      { key: 'closeBtn', label: 'Show Close Btn', type: 'boolean', default: true, category: 'specific' },
    ],
  },
  lv_spinbox: {
    type: 'lv_spinbox',
    label: 'Spinbox',
    icon: '🔢',
    defaultSize: { w: 120, h: 40 },
    canHaveChildren: false,
    properties: [
      { key: 'id', label: 'ID', type: 'text', default: '', category: 'basic' },
      { key: 'min', label: 'Min', type: 'number', default: 0, category: 'specific' },
      { key: 'max', label: 'Max', type: 'number', default: 100, category: 'specific' },
      { key: 'value', label: 'Value', type: 'number', default: 0, category: 'specific' },
      { key: 'step', label: 'Step', type: 'number', default: 1, category: 'specific' },
      { key: 'digitCount', label: 'Digit Count', type: 'number', default: 3, category: 'specific' },
      { key: 'rangeMode', label: 'Range Mode', type: 'boolean', default: false, category: 'specific' },
    ],
  },
  lv_spinner: {
    type: 'lv_spinner',
    label: 'Spinner',
    icon: '⏳',
    defaultSize: { w: 50, h: 50 },
    canHaveChildren: false,
    properties: [
      { key: 'id', label: 'ID', type: 'text', default: '', category: 'basic' },
      { key: 'speed', label: 'Spin Speed (ms)', type: 'number', default: 1000, category: 'specific' },
      { key: 'arcLength', label: 'Arc Length', type: 'number', default: 60, min: 0, max: 360, category: 'specific' },
      { key: 'arcAngle', label: 'Arc Angle', type: 'number', default: 300, min: 0, max: 360, category: 'specific' },
      { key: 'spinTime', label: 'Spin Time (ms)', type: 'number', default: 1000, category: 'specific' },
      { key: 'type', label: 'Type', type: 'select', default: 'spinning arc', options: [
        { label: 'Spinning Arc', value: 'LV_SPINNER_TYPE_SPINNING_ARC' },
        { label: 'Fill Arc', value: 'LV_SPINNER_TYPE_FILLSPIN_ARC' },
        { label: 'Const Arc', value: 'LV_SPINNER_TYPE_CONSTANT_ARC' },
      ], category: 'specific' },
    ],
  },
  lv_gauge: {
    type: 'lv_gauge',
    label: 'Gauge',
    icon: '🔄',
    defaultSize: { w: 200, h: 200 },
    canHaveChildren: false,
    properties: [
      { key: 'id', label: 'ID', type: 'text', default: '', category: 'basic' },
      { key: 'min', label: 'Min', type: 'number', default: 0, category: 'specific' },
      { key: 'max', label: 'Max', type: 'number', default: 100, category: 'specific' },
      { key: 'value', label: 'Value', type: 'number', default: 50, category: 'specific' },
      { key: 'criticalValue', label: 'Critical Value', type: 'number', default: 80, category: 'specific' },
      { key: 'labelCount', label: 'Label Count', type: 'number', default: 6, category: 'specific' },
      { key: 'lineCount', label: 'Line Count', type: 'number', default: 21, category: 'specific' },
      { key: 'needleColor', label: 'Needle Color', type: 'color', default: '#ff0000', category: 'specific' },
      { key: 'tickLabels', label: 'Show Tick Labels', type: 'boolean', default: true, category: 'specific' },
    ],
  },
  lv_scale: {
    type: 'lv_scale',
    label: 'Scale',
    icon: '📏',
    defaultSize: { w: 200, h: 50 },
    canHaveChildren: false,
    properties: [
      { key: 'id', label: 'ID', type: 'text', default: '', category: 'basic' },
      { key: 'min', label: 'Min', type: 'number', default: 0, category: 'specific' },
      { key: 'max', label: 'Max', type: 'number', default: 100, category: 'specific' },
      { key: 'majorTickCount', label: 'Major Tick Count', type: 'number', default: 5, category: 'specific' },
      { key: 'minorTickCount', label: 'Minor Tick Count', type: 'number', default: 3, category: 'specific' },
      { key: 'labelMod', label: 'Label Modulo', type: 'number', default: 1, category: 'specific' },
      { key: 'tickLength', label: 'Tick Length', type: 'number', default: 10, category: 'specific' },
      { key: 'rangeMode', label: 'Range Mode', type: 'boolean', default: false, category: 'specific' },
    ],
  },
  lv_keyboard: {
    type: 'lv_keyboard',
    label: 'Keyboard',
    icon: '⌨',
    defaultSize: { w: 320, h: 150 },
    canHaveChildren: false,
    properties: [
      { key: 'id', label: 'ID', type: 'text', default: '', category: 'basic' },
      { key: 'mode', label: 'Mode', type: 'select', default: 'text', options: [
        { label: 'Text', value: 'LV_KEYBOARD_MODE_TEXT' },
        { label: 'Number', value: 'LV_KEYBOARD_MODE_NUMBER' },
        { label: 'Special', value: 'LV_KEYBOARD_MODE_SPECIAL' },
      ], category: 'specific' },
      { key: 'popovers', label: 'Popovers', type: 'boolean', default: true, category: 'specific' },
    ],
  },
  lv_list: {
    type: 'lv_list',
    label: 'List',
    icon: '📋',
    defaultSize: { w: 200, h: 300 },
    canHaveChildren: true,
    properties: [
      { key: 'id', label: 'ID', type: 'text', default: '', category: 'basic' },
      { key: 'items', label: 'Items (comma)', type: 'text', default: 'Item 1,Item 2,Item 3', category: 'specific' },
    ],
  },
  lv_linemeter: {
    type: 'lv_linemeter',
    label: 'Line Meter',
    icon: '📐',
    defaultSize: { w: 150, h: 150 },
    canHaveChildren: false,
    properties: [
      { key: 'id', label: 'ID', type: 'text', default: '', category: 'basic' },
      { key: 'min', label: 'Min', type: 'number', default: 0, category: 'specific' },
      { key: 'max', label: 'Max', type: 'number', default: 100, category: 'specific' },
      { key: 'value', label: 'Value', type: 'number', default: 50, category: 'specific' },
      { key: 'angle', label: 'Arc Angle', type: 'number', default: 220, category: 'specific' },
      { key: 'rotation', label: 'Rotation', type: 'number', default: 90, category: 'specific' },
      { key: 'lineCount', label: 'Line Count', type: 'number', default: 31, category: 'specific' },
      { key: 'scaleLines', label: 'Scale Lines', type: 'boolean', default: true, category: 'specific' },
    ],
  },
  lv_canvas: {
    type: 'lv_canvas',
    label: 'Canvas',
    icon: '🎨',
    defaultSize: { w: 200, h: 200 },
    canHaveChildren: false,
    properties: [
      { key: 'id', label: 'ID', type: 'text', default: '', category: 'basic' },
      { key: 'bufSize', label: 'Buffer Size', type: 'number', default: 40000, category: 'specific' },
      { key: 'mode', label: 'Mode', type: 'select', default: 'RGB888', options: [
        { label: 'RGB888', value: 'LV_IMG_CF_TRUE_COLOR' },
        { label: 'RGB565', value: 'LV_IMG_CF_TRUE_COLOR_565' },
        { label: 'Alpha Only', value: 'LV_IMG_CF_ALPHA_8BIT' },
      ], category: 'specific' },
    ],
  },
  lv_line: {
    type: 'lv_line',
    label: 'Line',
    icon: '╱',
    defaultSize: { w: 100, h: 100 },
    canHaveChildren: false,
    properties: [
      { key: 'id', label: 'ID', type: 'text', default: '', category: 'basic' },
      { key: 'points', label: 'Points (x1,y1,x2,y2,...)', type: 'text', default: '0,0,50,50,100,0', category: 'specific' },
      { key: 'autoSize', label: 'Auto Size', type: 'boolean', default: true, category: 'specific' },
      { key: 'yInvert', label: 'Y Invert', type: 'boolean', default: false, category: 'specific' },
    ],
  },
  lv_tileview: {
    type: 'lv_tileview',
    label: 'Tile View',
    icon: '⊞',
    defaultSize: { w: 320, h: 240 },
    canHaveChildren: true,
    properties: [
      { key: 'id', label: 'ID', type: 'text', default: '', category: 'basic' },
      { key: 'tileW', label: 'Tile Width', type: 'number', default: 320, category: 'specific' },
      { key: 'tileH', label: 'Tile Height', type: 'number', default: 240, category: 'specific' },
      { key: 'activeTile', label: 'Active Tile (row,col)', type: 'text', default: '0,0', category: 'specific' },
      { key: 'animTime', label: 'Anim Time (ms)', type: 'number', default: 300, category: 'specific' },
    ],
  },
  lv_animimg: {
    type: 'lv_animimg',
    label: 'Animated Image',
    icon: '🎞',
    defaultSize: { w: 100, h: 100 },
    canHaveChildren: false,
    properties: [
      { key: 'id', label: 'ID', type: 'text', default: '', category: 'basic' },
      { key: 'sources', label: 'Sources (comma)', type: 'text', default: '', category: 'specific' },
      { key: 'speed', label: 'Speed (ms)', type: 'number', default: 500, category: 'specific' },
      { key: 'repeatCount', label: 'Repeat Count', type: 'number', default: 0, category: 'specific' },
    ],
  },
  lv_calendar: {
    type: 'lv_calendar',
    label: 'Calendar',
    icon: '📅',
    defaultSize: { w: 280, h: 250 },
    canHaveChildren: false,
    properties: [
      { key: 'id', label: 'ID', type: 'text', default: '', category: 'basic' },
      { key: 'year', label: 'Year', type: 'number', default: 2025, category: 'specific' },
      { key: 'month', label: 'Month', type: 'number', default: 1, min: 1, max: 12, category: 'specific' },
      { key: 'day', label: 'Day', type: 'number', default: 1, min: 1, max: 31, category: 'specific' },
      { key: 'highlightedDates', label: 'Highlighted Dates', type: 'text', default: '', category: 'specific' },
      { key: 'weekNumbers', label: 'Show Week Numbers', type: 'boolean', default: false, category: 'specific' },
      { key: 'todayBtn', label: 'Show Today Btn', type: 'boolean', default: true, category: 'specific' },
      { key: 'headerArrows', label: 'Header Arrows', type: 'boolean', default: true, category: 'specific' },
      { key: 'headerDropdown', label: 'Header Dropdown', type: 'boolean', default: true, category: 'specific' },
    ],
  },
  lv_colorwheel: {
    type: 'lv_colorwheel',
    label: 'Color Wheel',
    icon: '🎨',
    defaultSize: { w: 150, h: 150 },
    canHaveChildren: false,
    properties: [
      { key: 'id', label: 'ID', type: 'text', default: '', category: 'basic' },
      { key: 'color', label: 'Color', type: 'color', default: '#ff0000', category: 'specific' },
      { key: 'mode', label: 'Mode', type: 'select', default: 'hue', options: [
        { label: 'Hue', value: 'LV_COLORWHEEL_MODE_HUE' },
        { label: 'Saturation', value: 'LV_COLORWHEEL_MODE_SATURATION' },
        { label: 'Value', value: 'LV_COLORWHEEL_MODE_VALUE' },
      ], category: 'specific' },
      { key: 'knobRounded', label: 'Knob Rounded', type: 'boolean', default: true, category: 'specific' },
    ],
  },
  lv_menu: {
    type: 'lv_menu',
    label: 'Menu',
    icon: '☰',
    defaultSize: { w: 250, h: 300 },
    canHaveChildren: true,
    properties: [
      { key: 'id', label: 'ID', type: 'text', default: '', category: 'basic' },
      { key: 'rootBtnBgColor', label: 'Root Btn BG Color', type: 'color', default: '', category: 'style' },
      { key: 'sidebarVisible', label: 'Sidebar Visible', type: 'boolean', default: false, category: 'specific' },
    ],
  },
  lv_msg: {
    type: 'lv_msg',
    label: 'Message',
    icon: '✉',
    defaultSize: { w: 100, h: 50 },
    canHaveChildren: false,
    properties: [
      { key: 'id', label: 'ID', type: 'text', default: '', category: 'basic' },
      { key: 'msgId', label: 'Message ID', type: 'number', default: 0, category: 'specific' },
      { key: 'payload', label: 'Payload', type: 'text', default: '', category: 'specific' },
    ],
  },
  lv_roller: {
    type: 'lv_roller',
    label: 'Roller',
    icon: '☰',
    defaultSize: { w: 120, h: 120 },
    canHaveChildren: false,
    properties: [
      { key: 'id', label: 'ID', type: 'text', default: '', category: 'basic' },
      { key: 'options', label: 'Options (newline)', type: 'textarea', default: 'Option 1\nOption 2\nOption 3', category: 'specific' },
      { key: 'selected', label: 'Selected', type: 'number', default: 0, category: 'specific' },
      { key: 'rowCount', label: 'Visible Rows', type: 'number', default: 3, category: 'specific' },
      { key: 'mode', label: 'Mode', type: 'select', default: 'normal', options: [
        { label: 'Normal', value: 'LV_ROLLER_MODE_NORMAL' },
        { label: 'Infinite', value: 'LV_ROLLER_MODE_INFINITE' },
      ], category: 'specific' },
    ],
  },
  lv_span: {
    type: 'lv_span',
    label: 'Span',
    icon: 'A',
    defaultSize: { w: 100, h: 30 },
    canHaveChildren: false,
    properties: [
      { key: 'id', label: 'ID', type: 'text', default: '', category: 'basic' },
      { key: 'text', label: 'Text', type: 'text', default: 'Span text', category: 'basic' },
      { key: 'customColor', label: 'Custom Color', type: 'color', default: '', category: 'specific' },
    ],
  },
};

export const WIDGET_LIST = Object.values(WIDGET_DEFINITIONS);
