import type { LvglWidgetNode, LvglStyle, LvglWidgetType } from '../types/lvgl';
import { WIDGET_DEFINITIONS } from '../types/widgetDefinitions';

export function generateCode(widgets: LvglWidgetNode[], _screenW: number, _screenH: number): string {
  const lines: string[] = [];
  let hasContent = false;

  lines.push('/*');
  lines.push(' * LVGL 8.4 UI Code');
  lines.push(' * Generated by LVGL Web Editor');
  lines.push(' */');
  lines.push('');
  lines.push('#include "lvgl.h"');
  lines.push('');

  for (const widget of widgets) {
    generateWidgetCode(widget, lines, 'scr', 0);
    hasContent = true;
  }

  if (!hasContent) {
    lines.push('/* No widgets defined */');
    lines.push('void lv_ui_init(void) {');
    lines.push('    /* Add your UI code here */');
    lines.push('}');
  }

  lines.push('');
  return lines.join('\n');
}

function generateWidgetCode(
  widget: LvglWidgetNode,
  lines: string[],
  parentVar: string,
  depth: number
): void {
  const indent = '    '.repeat(depth + 1);
  const varName = sanitizeVarName(widget.id);
  const def = WIDGET_DEFINITIONS[widget.type];

  lines.push(`${indent}/* ${def?.label || widget.type} */`);

  // Create widget
  const createFn = getCreateFunction(widget.type);
  lines.push(`${indent}lv_obj_t * ${varName} = ${createFn}(${parentVar});`);

  // Set size
  if (widget.area.w !== (def?.defaultSize.w ?? 0) || widget.area.h !== (def?.defaultSize.h ?? 0)) {
    lines.push(`${indent}lv_obj_set_size(${varName}, ${widget.area.w}, ${widget.area.h});`);
  }

  // Set position
  lines.push(`${indent}lv_obj_set_pos(${varName}, ${widget.area.x}, ${widget.area.y});`);

  // Apply style properties
  const styleLines = generateStyleCode(widget.style, varName, indent);
  lines.push(...styleLines);

  // Widget-specific properties
  const specificLines = generateSpecificProps(widget, varName, indent);
  lines.push(...specificLines);

  // Event handlers
  for (const evt of widget.events) {
    const cbName = `${varName}_${evt.event}_cb`;
    lines.push(`${indent}static void ${cbName}(lv_event_t * e) {`);
    const evtLines = evt.code.split('\n').map(l => `${indent}    ${l}`);
    lines.push(...evtLines);
    lines.push(`${indent}}`);
    lines.push(`${indent}lv_obj_add_event_cb(${varName}, ${cbName}, LV_EVENT_${evt.event.toUpperCase()}, NULL);`);
  }

  lines.push('');

  // Generate children
  for (const child of widget.children) {
    generateWidgetCode(child, lines, varName, depth + 1);
  }
}

function getCreateFunction(type: LvglWidgetType): string {
  const map: Record<string, string> = {
    'lv_obj': 'lv_obj_create',
    'lv_btn': 'lv_btn_create',
    'lv_label': 'lv_label_create',
    'lv_slider': 'lv_slider_create',
    'lv_bar': 'lv_bar_create',
    'lv_arc': 'lv_arc_create',
    'lv_led': 'lv_led_create',
    'lv_switch': 'lv_switch_create',
    'lv_checkbox': 'lv_checkbox_create',
    'lv_dropdown': 'lv_dropdown_create',
    'lv_textarea': 'lv_textarea_create',
    'lv_img': 'lv_img_create',
    'lv_imgbtn': 'lv_imgbtn_create',
    'lv_btnmatrix': 'lv_btnmatrix_create',
    'lv_chart': 'lv_chart_create',
    'lv_table': 'lv_table_create',
    'lv_tabview': 'lv_tabview_create',
    'lv_win': 'lv_win_create',
    'lv_msgbox': 'lv_msgbox_create',
    'lv_spinbox': 'lv_spinbox_create',
    'lv_spinner': 'lv_spinner_create',
    'lv_gauge': 'lv_gauge_create',
    'lv_scale': 'lv_scale_create',
    'lv_keyboard': 'lv_keyboard_create',
    'lv_list': 'lv_list_create',
    'lv_linemeter': 'lv_linemeter_create',
    'lv_canvas': 'lv_canvas_create',
    'lv_line': 'lv_line_create',
    'lv_tileview': 'lv_tileview_create',
    'lv_animimg': 'lv_animimg_create',
    'lv_calendar': 'lv_calendar_create',
    'lv_colorwheel': 'lv_colorwheel_create',
    'lv_menu': 'lv_menu_create',
    'lv_roller': 'lv_roller_create',
  };
  return map[type] || 'lv_obj_create';
}

function generateStyleCode(style: LvglStyle, varName: string, indent: string): string[] {
  const lines: string[] = [];
  const s = style;

  if (s.bgColor) {
    lines.push(`${indent}lv_obj_set_style_bg_color(${varName}, lv_color_hex(${colorToHex(s.bgColor)}), 0);`);
  }
  if (s.bgOpacity !== undefined) {
    lines.push(`${indent}lv_obj_set_style_bg_opa(${varName}, ${s.bgOpacity}, 0);`);
  }
  if (s.borderWidth !== undefined) {
    lines.push(`${indent}lv_obj_set_style_border_width(${varName}, ${s.borderWidth}, 0);`);
  }
  if (s.borderColor) {
    lines.push(`${indent}lv_obj_set_style_border_color(${varName}, lv_color_hex(${colorToHex(s.borderColor)}), 0);`);
  }
  if (s.radius !== undefined) {
    lines.push(`${indent}lv_obj_set_style_radius(${varName}, ${s.radius}, 0);`);
  }
  if (s.textColor) {
    lines.push(`${indent}lv_obj_set_style_text_color(${varName}, lv_color_hex(${colorToHex(s.textColor)}), 0);`);
  }
  if (s.padTop !== undefined) lines.push(`${indent}lv_obj_set_style_pad_top(${varName}, ${s.padTop}, 0);`);
  if (s.padBottom !== undefined) lines.push(`${indent}lv_obj_set_style_pad_bottom(${varName}, ${s.padBottom}, 0);`);
  if (s.padLeft !== undefined) lines.push(`${indent}lv_obj_set_style_pad_left(${varName}, ${s.padLeft}, 0);`);
  if (s.padRight !== undefined) lines.push(`${indent}lv_obj_set_style_pad_right(${varName}, ${s.padRight}, 0);`);
  if (s.shadowWidth !== undefined) {
    lines.push(`${indent}lv_obj_set_style_shadow_width(${varName}, ${s.shadowWidth}, 0);`);
  }
  if (s.shadowColor) {
    lines.push(`${indent}lv_obj_set_style_shadow_color(${varName}, lv_color_hex(${colorToHex(s.shadowColor)}), 0);`);
  }
  if (s.shadowOffsetX !== undefined) lines.push(`${indent}lv_obj_set_style_shadow_ofs_x(${varName}, ${s.shadowOffsetX}, 0);`);
  if (s.shadowOffsetY !== undefined) lines.push(`${indent}lv_obj_set_style_shadow_ofs_y(${varName}, ${s.shadowOffsetY}, 0);`);
  if (s.lineWidth !== undefined) lines.push(`${indent}lv_obj_set_style_line_width(${varName}, ${s.lineWidth}, 0);`);
  if (s.lineColor) lines.push(`${indent}lv_obj_set_style_line_color(${varName}, lv_color_hex(${colorToHex(s.lineColor)}), 0);`);
  if (s.lineRounded !== undefined) lines.push(`${indent}lv_obj_set_style_line_rounded(${varName}, ${s.lineRounded ? 'true' : 'false'}, 0);`);
  if (s.opacity !== undefined) lines.push(`${indent}lv_obj_set_style_opa(${varName}, ${s.opacity}, 0);`);
  if (s.transformAngle !== undefined) lines.push(`${indent}lv_obj_set_style_transform_angle(${varName}, ${s.transformAngle * 10}, 0);`);
  if (s.transformZoom !== undefined) lines.push(`${indent}lv_obj_set_style_transform_zoom(${varName}, ${s.transformZoom}, 0);`);

  if (s.flexFlow) {
    lines.push(`${indent}lv_obj_set_flex_flow(${varName}, ${s.flexFlow});`);
  }
  if (s.flexGrow !== undefined) {
    lines.push(`${indent}lv_obj_set_flex_grow(${varName}, ${s.flexGrow});`);
  }

  if (s.layout !== undefined) {
    lines.push(`${indent}lv_obj_set_layout(${varName}, ${s.layout});`);
  }

  return lines;
}

function generateSpecificProps(widget: LvglWidgetNode, varName: string, indent: string): string[] {
  const lines: string[] = [];
  const props = widget.properties;

  switch (widget.type) {
    case 'lv_btn':
      if (props.checkable) {
        lines.push(`${indent}lv_btn_set_checkable(${varName}, true);`);
      }
      break;

    case 'lv_label':
      if (props.text) {
        lines.push(`${indent}lv_label_set_text(${varName}, "${escapeString(String(props.text))}");`);
      }
      if (props.longMode) {
        lines.push(`${indent}lv_label_set_long_mode(${varName}, ${props.longMode});`);
      }
      if (props.recolor) {
        lines.push(`${indent}lv_label_set_recolor(${varName}, true);`);
      }
      break;

    case 'lv_slider':
      lines.push(`${indent}lv_slider_set_range(${varName}, ${props.min ?? 0}, ${props.max ?? 100});`);
      lines.push(`${indent}lv_slider_set_value(${varName}, ${props.value ?? 50}, LV_ANIM_OFF);`);
      if (props.mode) {
        lines.push(`${indent}lv_slider_set_mode(${varName}, ${props.mode});`);
      }
      break;

    case 'lv_bar':
      lines.push(`${indent}lv_bar_set_range(${varName}, ${props.min ?? 0}, ${props.max ?? 100});`);
      lines.push(`${indent}lv_bar_set_value(${varName}, ${props.value ?? 50}, ${Number(props.animDuration ?? 0) > 0 ? 'LV_ANIM_ON' : 'LV_ANIM_OFF'});`);
      if (props.rangeMode) {
        lines.push(`${indent}lv_bar_set_mode(${varName}, LV_BAR_MODE_RANGE);`);
      }
      break;

    case 'lv_arc':
      lines.push(`${indent}lv_arc_set_range(${varName}, ${props.min ?? 0}, ${props.max ?? 100});`);
      lines.push(`${indent}lv_arc_set_value(${varName}, ${props.value ?? 50});`);
      lines.push(`${indent}lv_arc_set_bg_angles(${varName}, ${props.startAngle ?? 135}, ${props.endAngle ?? 270});`);
      if (props.rotation) {
        lines.push(`${indent}lv_arc_set_rotation(${varName}, ${props.rotation});`);
      }
      if (props.type) {
        lines.push(`${indent}lv_arc_set_mode(${varName}, ${props.type});`);
      }
      if (props.changeRate) {
        lines.push(`${indent}lv_arc_set_change_rate(${varName}, ${props.changeRate});`);
      }
      break;

    case 'lv_switch':
      if (props.checked) {
        lines.push(`${indent}lv_obj_add_state(${varName}, LV_STATE_CHECKED);`);
      }
      break;

    case 'lv_checkbox':
      if (props.text) {
        lines.push(`${indent}lv_checkbox_set_text(${varName}, "${escapeString(String(props.text))}");`);
      }
      if (props.checked) {
        lines.push(`${indent}lv_obj_add_state(${varName}, LV_STATE_CHECKED);`);
      }
      break;

    case 'lv_dropdown':
      if (props.options) {
        const opts = String(props.options).split('\n').map(s => s.trim()).filter(s => s);
        lines.push(`${indent}lv_dropdown_set_options(${varName}, "${escapeString(opts.join('\\n'))}");`);
      }
      if (props.selected) {
        lines.push(`${indent}lv_dropdown_set_selected(${varName}, ${props.selected});`);
      }
      if (props.dir) {
        lines.push(`${indent}lv_dropdown_set_dir(${varName}, ${props.dir});`);
      }
      if (props.maxHeight) {
        lines.push(`${indent}lv_dropdown_set_max_height(${varName}, ${props.maxHeight});`);
      }
      break;

    case 'lv_textarea':
      if (props.text) {
        lines.push(`${indent}lv_textarea_set_text(${varName}, "${escapeString(String(props.text))}");`);
      }
      if (props.placeholder) {
        lines.push(`${indent}lv_textarea_set_placeholder_text(${varName}, "${escapeString(String(props.placeholder))}");`);
      }
      if (props.maxLength) {
        lines.push(`${indent}lv_textarea_set_max_length(${varName}, ${props.maxLength});`);
      }
      if (props.passwordMode) {
        lines.push(`${indent}lv_textarea_set_password_mode(${varName}, true);`);
      }
      if (props.oneLine) {
        lines.push(`${indent}lv_textarea_set_one_line(${varName}, true);`);
      }
      if (props.acceptedChars) {
        lines.push(`${indent}lv_textarea_set_accepted_chars(${varName}, "${escapeString(String(props.acceptedChars))}");`);
      }
      break;

    case 'lv_img':
      if (props.src) {
        lines.push(`${indent}lv_img_set_src(${varName}, "${escapeString(String(props.src))}");`);
      }
      if (props.angle) {
        lines.push(`${indent}lv_img_set_angle(${varName}, ${Number(props.angle) * 10});`);
      }
      if (props.zoom && Number(props.zoom) !== 256) {
        lines.push(`${indent}lv_img_set_zoom(${varName}, ${props.zoom});`);
      }
      if (props.autoSize === false) {
        lines.push(`${indent}lv_img_set_auto_size(${varName}, false);`);
      }
      break;

    case 'lv_imgbtn':
      if (props.srcReleased) {
        lines.push(`${indent}lv_imgbtn_set_src(${varName}, LV_IMGBTN_STATE_RELEASED, NULL, "${escapeString(String(props.srcReleased))}", NULL);`);
      }
      if (props.srcPressed) {
        lines.push(`${indent}lv_imgbtn_set_src(${varName}, LV_IMGBTN_STATE_PRESSED, NULL, "${escapeString(String(props.srcPressed))}", NULL);`);
      }
      if (props.checkable) {
        lines.push(`${indent}lv_btn_set_checkable(${varName}, true);`);
      }
      break;

    case 'lv_btnmatrix':
      if (props.map) {
        const btnMap = String(props.map).split('\n').map(row => `"${escapeString(row)}"`).join(', ') + ', ""';
        lines.push(`${indent}static const char * ${varName}_map[] = {${btnMap}};`);
        lines.push(`${indent}lv_btnmatrix_set_map(${varName}, ${varName}_map);`);
      }
      break;

    case 'lv_chart':
      lines.push(`${indent}lv_chart_set_type(${varName}, ${props.type ?? 'LV_CHART_TYPE_LINE'});`);
      lines.push(`${indent}lv_chart_set_range(${varName}, LV_CHART_AXIS_PRIMARY_Y, ${props.rangeMin ?? 0}, ${props.rangeMax ?? 100});`);
      lines.push(`${indent}lv_chart_set_point_count(${varName}, ${props.pointCount ?? 10});`);
      if (props.divLineX === false) {
        lines.push(`${indent}lv_chart_set_div_line_count(${varName}, 0, ${props.divLineY !== false ? 1 : 0});`);
      }
      if (props.updateMode) {
        lines.push(`${indent}lv_chart_set_update_mode(${varName}, ${props.updateMode});`);
      }
      break;

    case 'lv_table':
      if (props.colCount && props.rowCount) {
        let w = widget.area.w;
        const colW = Math.floor(w / Number(props.colCount));
        lines.push(`${indent}lv_table_set_col_cnt(${varName}, ${props.colCount});`);
        lines.push(`${indent}lv_table_set_row_cnt(${varName}, ${props.rowCount});`);
        for (let c = 0; c < Number(props.colCount); c++) {
          lines.push(`${indent}lv_table_set_col_width(${varName}, ${c}, ${colW});`);
        }
      }
      break;

    case 'lv_tabview':
      if (props.tabNames) {
        const tabs = String(props.tabNames).split(',').map(s => s.trim());
        for (const tab of tabs) {
          lines.push(`${indent}lv_tabview_add_tab(${varName}, "${escapeString(tab)}");`);
        }
      }
      break;

    case 'lv_win':
      if (props.title) {
        lines.push(`${indent}lv_win_set_title(${varName}, "${escapeString(String(props.title))}");`);
      }
      break;

    case 'lv_msgbox':
      if (props.title) {
        lines.push(`${indent}lv_msgbox_set_title(${varName}, "${escapeString(String(props.title))}");`);
      }
      if (props.text) {
        lines.push(`${indent}lv_msgbox_set_text(${varName}, "${escapeString(String(props.text))}");`);
      }
      if (props.buttons && !props._btnsAdded) {
        props._btnsAdded = true;
        const btns = String(props.buttons).split(',').map(s => `"${escapeString(s.trim())}"`).join(', ') + ', ""';
        lines.push(`${indent}static const char * ${varName}_btns[] = {${btns}};`);
        lines.push(`${indent}lv_msgbox_add_btns(${varName}, ${varName}_btns);`);
      }
      break;

    case 'lv_spinbox':
      lines.push(`${indent}lv_spinbox_set_range(${varName}, ${props.min ?? 0}, ${props.max ?? 100});`);
      lines.push(`${indent}lv_spinbox_set_value(${varName}, ${props.value ?? 0});`);
      lines.push(`${indent}lv_spinbox_set_step(${varName}, ${props.step ?? 1});`);
      lines.push(`${indent}lv_spinbox_set_digit_format(${varName}, ${props.digitCount ?? 3}, 0);`);
      break;

    case 'lv_spinner':
      lines.push(`${indent}lv_spinner_set_anim_params(${varName}, ${props.speed ?? 1000}, ${props.arcLength ?? 60});`);
      break;

    case 'lv_gauge':
      lines.push(`${indent}lv_gauge_set_range(${varName}, ${props.min ?? 0}, ${props.max ?? 100});`);
      lines.push(`${indent}lv_gauge_set_value(${varName}, 0, ${props.value ?? 50});`);
      if (props.criticalValue) {
        lines.push(`${indent}lv_gauge_set_critical_value(${varName}, ${props.criticalValue});`);
      }
      if (props.labelCount) {
        lines.push(`${indent}lv_gauge_set_scale(${varName}, ${props.angle ?? 220}, ${props.lineCount ?? 21}, ${props.labelCount});`);
      }
      if (props.needleColor) {
        lines.push(`${indent}lv_gauge_set_needle_color(${varName}, 0, lv_color_hex(${colorToHex(String(props.needleColor))}));`);
      }
      break;

    case 'lv_scale':
      lines.push(`${indent}lv_scale_set_range(${varName}, ${props.min ?? 0}, ${props.max ?? 100});`);
      lines.push(`${indent}lv_scale_set_total_tick_count(${varName}, ${(Number(props.majorTickCount ?? 5)) * (Number(props.minorTickCount ?? 3))});`);
      if (props.majorTickCount) {
        lines.push(`${indent}lv_scale_set_major_tick_every(${varName}, ${props.minorTickCount ?? 3});`);
      }
      if (props.tickLength) {
        lines.push(`${indent}lv_scale_set_tick_length(${varName}, ${props.tickLength});`);
      }
      break;

    case 'lv_keyboard':
      if (props.mode) {
        lines.push(`${indent}lv_keyboard_set_mode(${varName}, ${props.mode});`);
      }
      if (props.popovers) {
        lines.push(`${indent}lv_keyboard_set_popovers(${varName}, true);`);
      }
      break;

    case 'lv_list':
      if (props.items) {
        const items = String(props.items).split(',').map(s => s.trim());
        for (const item of items) {
          lines.push(`${indent}lv_list_add_text(${varName}, "${escapeString(item)}");`);
        }
      }
      break;

    case 'lv_linemeter':
      lines.push(`${indent}lv_linemeter_set_range(${varName}, ${props.min ?? 0}, ${props.max ?? 100});`);
      lines.push(`${indent}lv_linemeter_set_value(${varName}, ${props.value ?? 50});`);
      if (props.angle) {
        lines.push(`${indent}lv_linemeter_set_scale(${varName}, ${props.angle}, ${props.lineCount ?? 31});`);
      }
      break;

    case 'lv_canvas':
      lines.push(`${indent}// Canvas buffer: ${props.bufSize ?? 40000} bytes (${props.mode || 'LV_IMG_CF_TRUE_COLOR'})`);
      break;

    case 'lv_line':
      if (props.points) {
        const nums = String(props.points).split(',').map(s => Number(s.trim()));
        const pts: string[] = [];
        for (let i = 0; i < nums.length; i += 2) {
          pts.push(`{${nums[i]}, ${nums[i + 1] ?? 0}}`);
        }
        lines.push(`${indent}static lv_point_t ${varName}_points[] = {${pts.join(', ')}};`);
        lines.push(`${indent}lv_line_set_points(${varName}, ${varName}_points, ${pts.length});`);
      }
      break;

    case 'lv_tileview':
      lines.push(`${indent}lv_tileview_set_tile_size(${varName}, ${props.tileW ?? 320}, ${props.tileH ?? 240});`);
      break;

    case 'lv_animimg':
      if (props.speed) {
        lines.push(`${indent}lv_animimg_set_duration(${varName}, ${props.speed});`);
      }
      if (props.repeatCount) {
        lines.push(`${indent}lv_animimg_set_repeat_count(${varName}, ${props.repeatCount});`);
      }
      break;

    case 'lv_calendar':
      if (props.year && props.month) {
        lines.push(`${indent}lv_calendar_set_today_date(${varName}, ${props.year}, ${props.month}, ${props.day ?? 1});`);
        lines.push(`${indent}lv_calendar_set_showed_date(${varName}, ${props.year}, ${props.month});`);
      }
      break;

    case 'lv_colorwheel':
      if (props.color) {
        lines.push(`${indent}lv_colorwheel_set_color(${varName}, lv_color_hex(${colorToHex(String(props.color))}));`);
      }
      if (props.mode) {
        lines.push(`${indent}lv_colorwheel_set_mode(${varName}, ${props.mode});`);
      }
      break;

    case 'lv_led':
      if (props.brightness) {
        lines.push(`${indent}lv_led_set_brightness(${varName}, ${props.brightness});`);
      }
      if (props.onColor) {
        lines.push(`${indent}lv_led_set_color(${varName}, lv_color_hex(${colorToHex(String(props.onColor))}));`);
      }
      break;

    case 'lv_menu':
      if (props.rootBtnBgColor) {
        lines.push(`${indent}lv_menu_set_page_sidebar_colors(${varName}, lv_color_hex(${colorToHex(String(props.rootBtnBgColor))}));`);
      }
      break;
  }

  return lines;
}

function sanitizeVarName(id: string): string {
  return 'ui_' + id.replace(/[^a-zA-Z0-9_]/g, '_').replace(/_+/g, '_');
}

function escapeString(str: string): string {
  return str
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t');
}

function colorToHex(color: string): string {
  if (color.startsWith('#')) {
    return '0x' + color.slice(1);
  }
  return '0x000000';
}
