import JSZip from 'jszip';
import type { LvglWidgetNode } from '../types/lvgl';
import { generateCode } from './index';
import { BOARDS, type BoardDefinition } from './boards';

export function generatePicoProject(
  widgets: LvglWidgetNode[],
  screenW: number,
  screenH: number,
  boardId: string,
  useFreeRtos: boolean = false
): JSZip {
  const board = BOARDS.find(b => b.id === boardId) || BOARDS[0];
  const zip = new JSZip();
  const uiCode = generateCode(widgets, screenW, screenH);

  zip.file('CMakeLists.txt', generateCMake(board, useFreeRtos));
  zip.file('main.c', generateMainC(uiCode, board, screenW, screenH, useFreeRtos));
  zip.file('lv_conf.h', generateLvConf(board));
  zip.file('pico_sdk_import.cmake', picoSdkImportCmake);
  zip.file(`boards/${board.boardHeaderFile}`, board.boardHeaderContent);
  zip.file('port/lv_port_disp.c', generatePortDisp(board));
  zip.file('port/lv_port_disp.h', portDispHeader);
  zip.file('port/lv_port_indev.c', generatePortIndev(board));
  zip.file('port/lv_port_indev.h', portIndevHeader);
  zip.file('.vscode/launch.json', generateLaunchJson(board));
  zip.file('.vscode/settings.json', vscodeSettings);

  if (useFreeRtos) {
    zip.file('FreeRTOSConfig.h', generateFreeRtosConfig(board));
  }

  return zip;
}

/* ============================================================ */
/* CMakeLists.txt                                                */
/* ============================================================ */
function generateCMake(board: BoardDefinition, useFreeRtos: boolean = false): string {
  const cl = board.chip;
  return [
    'cmake_minimum_required(VERSION 3.20)',
    `project(lvgl_${cl})`,
    '',
    'include(pico_sdk_import.cmake)',
    'pico_sdk_init()',
    '',
    '# Board definition',
    `set(PICO_BOARD ${board.id})`,
    'set(PICO_BOARD_HEADER_DIRS ${CMAKE_CURRENT_SOURCE_DIR}/boards)',
    '',
    '# LVGL config',
    'add_compile_options(-DLV_CONF_INCLUDE_SIMPLE)',
    'add_compile_options(-DLV_LVGL_H_INCLUDE_SIMPLE)',
    '',
    '# Create executable',
    `add_executable(lvgl_${cl}`,
    '    main.c',
    '    port/lv_port_disp.c',
    '    port/lv_port_indev.c',
    ')',
    '',
    '# Link Pico SDK libraries',
    `target_link_libraries(lvgl_${cl}`,
    '    pico_stdlib',
    '    hardware_i2c',
    '    hardware_spi',
    '    hardware_pwm',
    '    hardware_dma',
    '    hardware_pio',
    '    hardware_irq',
    '    hardware_gpio',
    '    pico_multicore',
    '    pico_time',
    ')',
    '',
    '# Link BSP libraries',
    ...(board.bspLibs.length > 0 ? board.bspLibs.map(l => `target_link_libraries(lvgl_${cl} ${l})`) : ['# No BSP libraries specified']),
    '',
    '# Add LVGL',
    'add_subdirectory(lvgl)',
    '',
    '# Include directories',
    `target_include_directories(lvgl_${cl} PRIVATE`,
    '    ${CMAKE_CURRENT_SOURCE_DIR}',
    '    ${CMAKE_CURRENT_SOURCE_DIR}/lvgl',
    '    ${CMAKE_CURRENT_SOURCE_DIR}/port',
    '    ${CMAKE_CURRENT_SOURCE_DIR}/boards',
    ...(board.bspHeaders.length > 0 ? ['    ${CMAKE_CURRENT_SOURCE_DIR}/bsp/include'] : []),
    ')',
    '',
    ...(useFreeRtos ? [
      '',
      '# FreeRTOS',
      'add_compile_options(-DUSE_FREERTOS)',
      'add_subdirectory(FreeRTOS_Kernel)',
      `target_include_directories(lvgl_${cl} PRIVATE`,
      '    ${CMAKE_CURRENT_SOURCE_DIR}/FreeRTOS_Kernel/include',
      '    ${CMAKE_CURRENT_SOURCE_DIR}/FreeRTOS_Kernel/portable/ThirdParty/GCC/RP2350_ARM_NTZ/non_secure',
      ')',
      `target_link_libraries(lvgl_${cl} FreeRTOS_Kernel pico_multicore)`,
    ] : []),
    '# Output',
    `set_target_properties(lvgl_${cl} PROPERTIES OUTPUT_NAME "lvgl_${cl}")`,
    `pico_add_extra_outputs(lvgl_${cl})`,
    `pico_enable_stdio_uart(lvgl_${cl} 1)`,
    `pico_enable_stdio_usb(lvgl_${cl} 0)`,
    '',
  ].join('\n');
}

/* ============================================================ */
/* main.c                                                        */
/* ============================================================ */
function generateMainC(uiCode: string, board: BoardDefinition, _sw: number, _sh: number, useFreeRtos: boolean = false): string {
  const uiLines = uiCode.split('\n').filter(l => !l.startsWith('#include "lvgl.h"'));
  const uiFiltered = uiLines.join('\n');
  const isRgb = board.display.type === 'rgb';

  if (useFreeRtos) {
    return [
      '/*',
      ` * LVGL UI for ${board.name} (FreeRTOS)`,
      ` * Display: ${board.resolution.w}x${board.resolution.h}`,
      ' * Generated by LVGL Web Editor',
      ' */',
      '',
      '#include <stdio.h>',
      '#include "pico/stdlib.h"',
      '#include "hardware/i2c.h"',
      '#include "lvgl.h"',
      '#include "FreeRTOS.h"',
      '#include "task.h"',
      '',
      '#include "port/lv_port_disp.h"',
      '#include "port/lv_port_indev.h"',
      '',
      ...(isRgb ? ['#include "bsp_i2c.h"'] : []),
      '',
      `#define LVGL_TICK_PERIOD_MS 10`,
      `#define LVGL_TASK_STACK_SIZE 4096`,
      `#define LVGL_TASK_PRIORITY (tskIDLE_PRIORITY + 2)`,
      '',
      `static void set_cpu_clock(void) {`,
      `    set_sys_clock_khz(${board.cpuClock} * 1000, true);`,
      `    clock_configure(clk_peri, 0,`,
      `        CLOCKS_CLK_PERI_CTRL_AUXSRC_VALUE_CLKSRC_PLL_SYS,`,
      `        ${board.cpuClock} * 1000 * 1000,`,
      `        ${board.cpuClock} * 1000 * 1000);`,
      `}`,
      '',
      'static void lvgl_task(void *arg) {',
      '    TickType_t last_wake = xTaskGetTickCount();',
      '    while (true) {',
      '        lv_timer_handler();',
      '        vTaskDelayUntil(&last_wake, pdMS_TO_TICKS(LVGL_TICK_PERIOD_MS));',
      '    }',
      '}',
      '',
      'int main() {',
      '    set_cpu_clock();',
      '    stdio_init_all();',
      ...(isRgb ? ['    bsp_i2c_init();'] : []),
      '    lv_init();',
      '    lv_port_disp_init();',
      '    lv_port_indev_init();',
      '',
      uiFiltered,
      '',
      '    xTaskCreate(lvgl_task, "lvgl", LVGL_TASK_STACK_SIZE, NULL, LVGL_TASK_PRIORITY, NULL);',
      '    vTaskStartScheduler();',
      '    return 0;',
      '}',
    ].join('\n');
  }

  return [
    '/*',
    ` * LVGL UI for ${board.name}`,
    ` * Display: ${board.resolution.w}x${board.resolution.h}`,
    ' * Generated by LVGL Web Editor',
    ' */',
    '',
    '#include <stdio.h>',
    '#include "pico/stdlib.h"',
    '#include "hardware/i2c.h"',
    '#include "lvgl.h"',
    '',
    '#include "port/lv_port_disp.h"',
    '#include "port/lv_port_indev.h"',
    '',
    ...(isRgb ? ['#include "bsp_i2c.h"'] : []),
    '',
    `#define LVGL_TICK_PERIOD_MS 10`,
    '',
    `static void set_cpu_clock(void) {`,
    `    set_sys_clock_khz(${board.cpuClock} * 1000, true);`,
    `    clock_configure(clk_peri, 0,`,
    `        CLOCKS_CLK_PERI_CTRL_AUXSRC_VALUE_CLKSRC_PLL_SYS,`,
    `        ${board.cpuClock} * 1000 * 1000,`,
    `        ${board.cpuClock} * 1000 * 1000);`,
    `}`,
    '',
    'static bool lvgl_tick_cb(struct repeating_timer *t) {',
    '    lv_tick_inc(LVGL_TICK_PERIOD_MS);',
    '    return true;',
    '}',
    '',
    'int main() {',
    '    static struct repeating_timer lvgl_timer;',
    '    set_cpu_clock();',
    '    stdio_init_all();',
    ...(isRgb ? ['    bsp_i2c_init();'] : []),
    '    lv_init();',
    '    lv_port_disp_init();',
    '    lv_port_indev_init();',
    '    add_repeating_timer_ms(LVGL_TICK_PERIOD_MS, lvgl_tick_cb, NULL, &lvgl_timer);',
    '',
    uiFiltered,
    '',
    '    while (true) {',
    '        lv_timer_handler();',
    '        sleep_ms(LVGL_TICK_PERIOD_MS);',
    '    }',
    '    return 0;',
    '}',
  ].join('\n');
}

/* ============================================================ */
/* lv_port_disp.c                                                */
/* ============================================================ */
function generatePortDisp(board: BoardDefinition): string {
  const res = board.resolution;
  const d = board.display;
  const W = res.w;
  const H = res.h;

  let displayInitBlock: string;
  let flushBlock: string;

  if (d.controller === 'ST7262') {
    displayInitBlock = [
      '    pio_rgb_info_t rgb_info;',
     `    rgb_info.width = ${W};`,
     `    rgb_info.height = ${H};`,
     `    rgb_info.transfer_size = ${d.transferSize || `${W} * 80`};`,
     `    rgb_info.pclk_freq = ${d.pclkFreq || 32000000};`,
     `    rgb_info.mode.double_buffer = ${d.doubleBuffer ? 'true' : 'false'};`,
      '    rgb_info.mode.enabled_transfer = true;',
     `    rgb_info.mode.enabled_psram = ${d.psram ? 'true' : 'false'};`,
     `    rgb_info.framebuffer1 = malloc(${W} * ${H} * sizeof(uint16_t));`,
      '    rgb_info.dma_flush_done_cb = disp_flush_done;',
      '',
      '    bsp_display_info_t display_info;',
     `    display_info.width = ${W};`,
     `    display_info.height = ${H};`,
      '    display_info.brightness = 80;',
      '    display_info.dma_flush_done_cb = disp_flush_done;',
      '    display_info.user_data = &rgb_info;',
      '',
      '    bsp_display_new_st7262(&display_if, &display_info);',
      '    display_if->init();',
    ].join('\n');

    flushBlock = [
      'static void disp_flush(lv_disp_drv_t *drv, const lv_area_t *area, lv_color_t *color_p) {',
      '    bsp_display_interface_t *di = (bsp_display_interface_t *)drv->user_data;',
      '    bsp_display_area_t da = { .x1 = area->x1, .x2 = area->x2, .y1 = area->y1, .y2 = area->y2 };',
      '    di->flush_dma(&da, color_p);',
      '}',
      '',
      'static void disp_flush_done(void) { lv_disp_flush_ready(&disp_drv); }',
    ].join('\n');
  } else if (d.controller === 'ST7701S') {
    displayInitBlock = [
      '    pio_rgb_info_t rgb_info;',
     `    rgb_info.width = ${W};`,
     `    rgb_info.height = ${H};`,
     `    rgb_info.transfer_size = ${d.transferSize || `${W} * 40`};`,
     `    rgb_info.pclk_freq = ${d.pclkFreq || 20000000};`,
     `    rgb_info.mode.double_buffer = ${d.doubleBuffer ? 'true' : 'false'};`,
      '    rgb_info.mode.enabled_transfer = true;',
     `    rgb_info.mode.enabled_psram = ${d.psram ? 'true' : 'false'};`,
     `    rgb_info.framebuffer1 = malloc(${W} * ${H} * sizeof(uint16_t));`,
      '    rgb_info.dma_flush_done_cb = NULL;',
      '',
      '    bsp_display_info_t display_info;',
     `    display_info.width = ${W};`,
     `    display_info.height = ${H};`,
      '    display_info.brightness = 80;',
      '    display_info.dma_flush_done_cb = NULL;',
      '    display_info.user_data = &rgb_info;',
      '',
      '    bsp_display_new_st7701s(&display_if, &display_info);',
      '    display_if->init();',
    ].join('\n');

    flushBlock = [
      'static void disp_flush(lv_disp_drv_t *drv, const lv_area_t *area, lv_color_t *color_p) {',
      '    bsp_display_interface_t *di = (bsp_display_interface_t *)drv->user_data;',
      '    bsp_display_area_t da = { .x1 = area->x1, .x2 = area->x2, .y1 = area->y1, .y2 = area->y2 };',
      '    di->flush_dma(&da, color_p);',
      '    lv_disp_flush_ready(drv);',
      '}',
    ].join('\n');
  } else if (d.controller === 'ST7701') {
    displayInitBlock = [
      '    pio_rgb_info_t rgb_info;',
     `    rgb_info.width = ${W};`,
     `    rgb_info.height = ${H};`,
     `    rgb_info.transfer_size = ${d.transferSize || `${W} * 240`};`,
     `    rgb_info.pclk_freq = ${d.pclkFreq || 20000000};`,
     `    rgb_info.mode.double_buffer = ${d.doubleBuffer ? 'true' : 'false'};`,
      '    rgb_info.mode.enabled_transfer = true;',
     `    rgb_info.mode.enabled_psram = ${d.psram ? 'true' : 'false'};`,
     `    rgb_info.framebuffer1 = malloc(${W} * ${H} * sizeof(uint16_t));`,
      '    rgb_info.dma_flush_done_cb = NULL;',
      '',
      '    bsp_display_info_t display_info;',
     `    display_info.width = ${W};`,
     `    display_info.height = ${H};`,
      '    display_info.brightness = 80;',
      '    display_info.dma_flush_done_cb = NULL;',
      '    display_info.user_data = &rgb_info;',
      '',
      '    bsp_display_new_st7701(&display_if, &display_info);',
      '    display_if->init();',
    ].join('\n');

    flushBlock = [
      'static void disp_flush(lv_disp_drv_t *drv, const lv_area_t *area, lv_color_t *color_p) {',
      '    bsp_display_interface_t *di = (bsp_display_interface_t *)drv->user_data;',
      '    bsp_display_area_t da = { .x1 = area->x1, .x2 = area->x2, .y1 = area->y1, .y2 = area->y2 };',
      '    di->flush_dma(&da, color_p);',
      '    lv_disp_flush_ready(drv);',
      '}',
    ].join('\n');
  } else {
    displayInitBlock = [
      '    /* TODO: Initialize your SPI/parallel display */',
      '    /* Example: spi_init(spi1, 62500 * 1000); */',
      '    /* Example: gpio_set_function(display_dc_pin, GPIO_FUNC_SPI); */',
      '    /* Example: ili9341_init(W, H); */',
    ].join('\n');

    flushBlock = [
      'static void disp_flush(lv_disp_drv_t *drv, const lv_area_t *area, lv_color_t *color_p) {',
      '    /* TODO: Send pixel data to your display */',
      '    /* set_window(area->x1, area->y1, area->x2, area->y2); */',
      '    /* write_data((uint8_t *)color_p, w * h * 2); */',
      '    lv_disp_flush_ready(drv);',
      '}',
    ].join('\n');
  }

  return [
    '#if 1',
    '',
    '#include "lv_port_disp.h"',
    '#include <stdbool.h>',
    '#include <stdlib.h>',
    ...(d.type === 'rgb' ? ['#include "pio_rgb.h"', `#include "bsp_${d.controller.toLowerCase()}.h"`] : []),
    '',
    `#define MY_DISP_HOR_RES (${W})`,
    `#define MY_DISP_VER_RES (${H})`,
    '',
    ...(d.type === 'rgb' ? [
      'bsp_display_interface_t *display_if;',
      `static lv_color_t *buf_1;`,
      `static lv_disp_drv_t disp_drv;`,
    ] : [
      `static lv_color_t buf_1[MY_DISP_HOR_RES * 30];`,
      `static lv_disp_drv_t disp_drv;`,
    ]),
    '',
    flushBlock,
    '',
    'void lv_port_disp_init(void) {',
    ...(d.type === 'rgb' ? [displayInitBlock] : [
      displayInitBlock,
    ]),
    '',
    '    static lv_disp_draw_buf_t draw_buf_dsc;',
    ...(d.type === 'rgb' ? [
     `    buf_1 = malloc(MY_DISP_HOR_RES * 10 * sizeof(lv_color_t));`,
     `    lv_disp_draw_buf_init(&draw_buf_dsc, buf_1, NULL, MY_DISP_HOR_RES * 10);`,
    ] : [
     `    lv_disp_draw_buf_init(&draw_buf_dsc, buf_1, NULL, MY_DISP_HOR_RES * 30);`,
    ]),
    '',
    '    lv_disp_drv_init(&disp_drv);',
    '    disp_drv.hor_res = MY_DISP_HOR_RES;',
    '    disp_drv.ver_res = MY_DISP_VER_RES;',
    '    disp_drv.flush_cb = disp_flush;',
    '    disp_drv.draw_buf = &draw_buf_dsc;',
    ...(d.type === 'rgb' ? ['    disp_drv.user_data = display_if;'] : []),
    '    lv_disp_drv_register(&disp_drv);',
    '}',
    '',
    '#endif /*LV_PORT_DISP_H*/',
  ].join('\n');
}

const portDispHeader = [
  '#ifndef LV_PORT_DISP_H',
  '#define LV_PORT_DISP_H',
  '',
  '#ifdef __cplusplus',
  'extern "C" {',
  '#endif',
  '',
  '#include "lvgl/lvgl.h"',
  '',
  'void lv_port_disp_init(void);',
  '',
  '#ifdef __cplusplus',
  '}',
  '#endif',
  '',
  '#endif',
].join('\n');

/* ============================================================ */
/* lv_port_indev.c                                               */
/* ============================================================ */
function generatePortIndev(board: BoardDefinition): string {
  const res = board.resolution;

  const isGt911 = board.touch.controller === 'GT911';
  const touchHeader = isGt911 ? 'bsp_gt911.h' : 'bsp_touch.h';
  const touchNewFn = isGt911
    ? 'bsp_touch_new_gt911(&touch_if, &touch_info)'
    : '/* TODO: Initialize your touch controller */';

  return [
    '#if 1',
    '',
    '#include "lv_port_indev.h"',
    '#include "lvgl.h"',
    `#include "${touchHeader}"`,
    '',
    'static lv_indev_t *indev_touchpad;',
    '',
    'static void touchpad_read(lv_indev_drv_t *drv, lv_indev_data_t *data) {',
    '    static lv_coord_t last_x = 0, last_y = 0;',
    ...(isGt911 ? [
      '    bsp_touch_data_t touch_data;',
      '    bsp_touch_interface_t *touch_if = (bsp_touch_interface_t *)drv->user_data;',
      '    touch_if->read();',
      '    if (touch_if->get_data(&touch_data)) {',
      '        data->point.x = touch_data.x;',
      '        data->point.y = touch_data.y;',
      '        data->state = LV_INDEV_STATE_PRESSED;',
      '        last_x = touch_data.x;',
      '        last_y = touch_data.y;',
      '    } else {',
      '        data->point.x = last_x;',
      '        data->point.y = last_y;',
      '        data->state = LV_INDEV_STATE_RELEASED;',
      '    }',
    ] : [
      '    /* TODO: Read touch coordinates */',
      '    data->state = LV_INDEV_STATE_RELEASED;',
    ]),
    '}',
    '',
    'void lv_port_indev_init(void) {',
    '    static lv_indev_drv_t indev_drv;',
    '',
    ...(isGt911 ? [
      '    bsp_touch_interface_t *touch_if;',
      '    bsp_touch_info_t touch_info;',
     `    touch_info.width = ${res.w};`,
     `    touch_info.height = ${res.h};`,
      '    touch_info.rotation = 0;',
      `    ${touchNewFn};`,
      '    touch_if->init();',
    ] : [
      '    /* TODO: Initialize touch controller */',
    ]),
    '',
    '    lv_indev_drv_init(&indev_drv);',
    '    indev_drv.type = LV_INDEV_TYPE_POINTER;',
    '    indev_drv.read_cb = touchpad_read;',
    ...(isGt911 ? ['    indev_drv.user_data = touch_if;'] : []),
    '    indev_touchpad = lv_indev_drv_register(&indev_drv);',
    '}',
    '',
    '#endif',
  ].join('\n');
}

const portIndevHeader = [
  '#ifndef LV_PORT_INDEV_H',
  '#define LV_PORT_INDEV_H',
  '',
  '#ifdef __cplusplus',
  'extern "C" {',
  '#endif',
  '',
  '#include "lvgl/lvgl.h"',
  '',
  'void lv_port_indev_init(void);',
  '',
  '#ifdef __cplusplus',
  '}',
  '#endif',
  '',
  '#endif',
].join('\n');

/* ============================================================ */
/* lv_conf.h                                                     */
/* ============================================================ */
function generateLvConf(board: BoardDefinition): string {
  const W = board.resolution.w;
  const H = board.resolution.h;
  return [
    '#ifndef LV_CONF_H',
    '#define LV_CONF_H',
    '',
    '#include <stdint.h>',
    '',
    '#define LV_COLOR_DEPTH 16',
    '#define LV_COLOR_16_SWAP 0',
    '#define LV_COLOR_SCREEN_TRANSP 0',
    '',
    '#define LV_MEM_CUSTOM 1',
    '#if LV_MEM_CUSTOM == 0',
    '#define LV_MEM_SIZE (48 * 1024)',
    '#else',
    '#define LV_MEM_CUSTOM_INCLUDE <stdlib.h>',
    '#define LV_MEM_CUSTOM_ALLOC   malloc',
    '#define LV_MEM_CUSTOM_FREE    free',
    '#define LV_MEM_CUSTOM_REALLOC realloc',
    '#endif',
    '',
    '#define LV_HOR_RES_MAX ' + String(W),
    '#define LV_VER_RES_MAX ' + String(H),
    '#define LV_DPI 100',
    '',
    '#define LV_USE_BTN 1',
    '#define LV_USE_LABEL 1',
    '#define LV_USE_SLIDER 1',
    '#define LV_USE_BAR 1',
    '#define LV_USE_ARC 1',
    '#define LV_USE_SWITCH 1',
    '#define LV_USE_CHECKBOX 1',
    '#define LV_USE_DROPDOWN 1',
    '#define LV_USE_TEXTAREA 1',
    '#define LV_USE_IMG 1',
    '#define LV_USE_IMGBTN 1',
    '#define LV_USE_BTNMATRIX 1',
    '#define LV_USE_CHART 1',
    '#define LV_USE_TABLE 1',
    '#define LV_USE_TABVIEW 1',
    '#define LV_USE_WIN 1',
    '#define LV_USE_MSGBOX 1',
    '#define LV_USE_SPINBOX 1',
    '#define LV_USE_SPINNER 1',
    '#define LV_USE_GAUGE 1',
    '#define LV_USE_SCALE 1',
    '#define LV_USE_KEYBOARD 1',
    '#define LV_USE_LIST 1',
    '#define LV_USE_LINEMETER 1',
    '#define LV_USE_CANVAS 1',
    '#define LV_USE_LINE 1',
    '#define LV_USE_TILEVIEW 1',
    '#define LV_USE_ANIMIMG 1',
    '#define LV_USE_CALENDAR 1',
    '#define LV_USE_COLORWHEEL 1',
    '#define LV_USE_MENU 1',
    '#define LV_USE_ROLLER 1',
    '',
    '#define LV_USE_ANIMATION 1',
    '',
    '#define LV_USE_THEME_DEFAULT 1',
    '#define LV_USE_THEME_BASIC 1',
    '#define LV_USE_THEME_MONO 1',
    '',
    '#define LV_FONT_MONTSERRAT_12 1',
    '#define LV_FONT_MONTSERRAT_14 1',
    '#define LV_FONT_MONTSERRAT_16 1',
    '#define LV_FONT_MONTSERRAT_20 1',
    '#define LV_FONT_MONTSERRAT_24 1',
    '#define LV_FONT_DEFAULT &lv_font_montserrat_14',
    '',
    '#define LV_USE_LOG 0',
    '#define LV_USE_ASSERT_NULL 1',
    '#define LV_USE_ASSERT_MEM 1',
    '',
    '#endif /*LV_CONF_H*/',
  ].join('\n');
}

/* ============================================================ */
/* .vscode/launch.json                                           */
/* ============================================================ */
function generateLaunchJson(board: BoardDefinition): string {
  const chip = board.chip === 'rp2350' ? 'RP2350' : 'RP2040';
  const cl = board.chip;
  const target = chip === 'RP2350' ? 'rp2350' : 'rp2040';
  return JSON.stringify({
    version: '0.2.0',
    configurations: [
      {
        name: `Pico ${chip} (Debug)`,
        type: 'cortex-debug',
        request: 'launch',
        servertype: 'openocd',
        cwd: '${workspaceRoot}',
        runToMain: true,
        executable: `build/lvgl_${cl}.elf`,
        configFiles: [`interface/cmsis-dap.cfg`, `target/${target}.cfg`],
        searchDir: ['${env:PICO_OPENOCD_PATH}/scripts'],
      },
      {
        name: `Pico ${chip} (PicoProbe)`,
        type: 'cortex-debug',
        request: 'launch',
        servertype: 'openocd',
        cwd: '${workspaceRoot}',
        runToMain: true,
        executable: `build/lvgl_${cl}.elf`,
        configFiles: ['interface/picoprobe.cfg', `target/${target}.cfg`],
        searchDir: ['${env:PICO_OPENOCD_PATH}/scripts'],
      },
    ],
  }, null, 2);
}

const vscodeSettings = JSON.stringify({
  'cmake.configureOnOpen': true,
  'cmake.buildBeforeRun': true,
  'C_Cpp.default.configurationProvider': 'ms-vscode.cmake-tools',
  'C_Cpp.default.includePath': [
    '${workspaceFolder}/**',
    '${env:PICO_SDK_PATH}/**',
  ],
  'files.associations': { '*.c': 'c', '*.h': 'c' },
  'editor.formatOnSave': true,
  '[c]': { 'editor.defaultFormatter': 'ms-vscode.cpptools' },
}, null, 2);

/* ============================================================ */
/* pico_sdk_import.cmake                                         */
/* ============================================================ */
const picoSdkImportCmake = [
  '# Generated by LVGL Web Editor',
  '# Download from: https://github.com/raspberrypi/pico-sdk/raw/master/external/pico_sdk_import.cmake',
  '',
  'if (DEFINED ENV{PICO_SDK_PATH} AND (NOT PICO_SDK_PATH))',
  '    set(PICO_SDK_PATH $ENV{PICO_SDK_PATH})',
  '    message("Using PICO_SDK_PATH from environment")',
  'endif()',
  '',
  'if (DEFINED ENV{PICO_SDK_FETCH_FROM_GIT} AND (NOT PICO_SDK_FETCH_FROM_GIT))',
  '    set(PICO_SDK_FETCH_FROM_GIT $ENV{PICO_SDK_FETCH_FROM_GIT})',
  '    message("Using PICO_SDK_FETCH_FROM_GIT from environment")',
  'endif()',
  '',
  'set(PICO_SDK_PATH "${PICO_SDK_PATH}" CACHE PATH "Path to Pico SDK")',
  'set(PICO_SDK_FETCH_FROM_GIT "${PICO_SDK_FETCH_FROM_GIT}" CACHE BOOL "Fetch SDK from git")',
  '',
  'if (NOT PICO_SDK_PATH)',
  '    message(FATAL_ERROR "PICO_SDK_PATH not set")',
  'endif()',
  '',
  'if (NOT EXISTS ${PICO_SDK_PATH}/pico_sdk_init.cmake)',
  '    message(FATAL_ERROR "PICO_SDK_PATH does not contain pico_sdk_init.cmake")',
  'endif()',
  '',
  'add_subdirectory(${PICO_SDK_PATH} pico_sdk)',
].join('\n');

/* ============================================================ */
/* FreeRTOSConfig.h                                              */
/* ============================================================ */
function generateFreeRtosConfig(board: BoardDefinition): string {
  return [
    '#ifndef FREERTOS_CONFIG_H',
    '#define FREERTOS_CONFIG_H',
    '',
    '#include "pico/stdlib.h"',
    '',
    '#define configUSE_PREEMPTION                    1',
    '#define configUSE_PORT_OPTIMISED_TASK_SELECTION 0',
    '#define configUSE_TICKLESS_IDLE                 0',
    '#define configCPU_CLOCK_HZ                      ' + String(board.cpuClock * 1000 * 1000),
    '#define configTICK_RATE_HZ                      1000',
    '#define configMAX_PRIORITIES                    32',
    '#define configMINIMAL_STACK_SIZE                128',
    '#define configTOTAL_HEAP_SIZE                   65536',
    '#define configMAX_TASK_NAME_LEN                 16',
    '#define configUSE_16_BIT_TICKS                  0',
    '#define configIDLE_SHOULD_YIELD                 1',
    '#define configUSE_TASK_NOTIFICATIONS            1',
    '#define configTASK_NOTIFICATION_ARRAY_ENTRIES   3',
    '#define configUSE_MUTEXES                       1',
    '#define configUSE_RECURSIVE_MUTEXES             1',
    '#define configUSE_COUNTING_SEMAPHORES           1',
    '#define configQUEUE_REGISTRY_SIZE               10',
    '#define configUSE_QUEUE_SETS                    1',
    '#define configUSE_TIME_SLICING                  1',
    '#define configUSE_NEWLIB_REENTRANT              0',
    '#define configENABLE_BACKWARD_COMPATIBILITY     0',
    '#define configNUM_THREAD_LOCAL_STORAGE_POINTERS 5',
    '#define configSTACK_DEPTH_TYPE                  uint16_t',
    '#define configMESSAGE_BUFFER_LENGTH_TYPE        size_t',
    '',
    '#define configSUPPORT_STATIC_ALLOCATION         0',
    '#define configSUPPORT_DYNAMIC_ALLOCATION        1',
    '#define configAPPLICATION_ALLOCATED_HEAP        0',
    '',
    '#define configUSE_IDLE_HOOK                     0',
    '#define configUSE_TICK_HOOK                     0',
    '#define configCHECK_FOR_STACK_OVERFLOW          2',
    '#define configUSE_MALLOC_FAILED_HOOK            0',
    '',
    '#define configGENERATE_RUN_TIME_STATS           0',
    '#define configUSE_TRACE_FACILITY                1',
    '#define configUSE_STATS_FORMATTING_FUNCTIONS    0',
    '',
    '#define configUSE_CO_ROUTINES                   0',
    '#define configUSE_DAEMON_TASK_STARTUP_HOOK      0',
    '#define configUSE_TIMERS                        1',
    '#define configTIMER_TASK_PRIORITY               (configMAX_PRIORITIES - 1)',
    '#define configTIMER_QUEUE_LENGTH                10',
    '#define configTIMER_TASK_STACK_DEPTH            256',
    '',
    '#define configUSE_POSIX_ERRNO                   1',
    '',
    '#ifdef __NVIC_PRIO_BITS',
    '#define configPRIO_BITS __NVIC_PRIO_BITS',
    '#else',
    '#define configPRIO_BITS 4',
    '#endif',
    '',
    '#define configLIBRARY_LOWEST_INTERRUPT_PRIORITY 15',
    '#define configLIBRARY_MAX_SYSCALL_INTERRUPT_PRIORITY 5',
    '#define configKERNEL_INTERRUPT_PRIORITY         (configLIBRARY_LOWEST_INTERRUPT_PRIORITY << (8 - configPRIO_BITS))',
    '#define configMAX_SYSCALL_INTERRUPT_PRIORITY    (configLIBRARY_MAX_SYSCALL_INTERRUPT_PRIORITY << (8 - configPRIO_BITS))',
    '',
    '#define INCLUDE_vTaskPrioritySet                1',
    '#define INCLUDE_uxTaskPriorityGet               1',
    '#define INCLUDE_vTaskDelete                     1',
    '#define INCLUDE_vTaskSuspend                    1',
    '#define INCLUDE_xTaskDelayUntil                 1',
    '#define INCLUDE_vTaskDelay                      1',
    '#define INCLUDE_xTaskGetSchedulerState          1',
    '#define INCLUDE_uxTaskGetStackHighWaterMark     1',
    '#define INCLUDE_xTaskGetCurrentTaskHandle       1',
    '#define INCLUDE_eTaskGetState                   1',
    '#define INCLUDE_xEventGroupSetBitFromISR        1',
    '#define INCLUDE_xTimerPendFunctionCall          1',
    '#define INCLUDE_xQueueGetMutexHolder            1',
    '#define INCLUDE_xSemaphoreGetMutexHolder        1',
    '#define INCLUDE_pcTaskGetTaskName               1',
    '',
    '#ifdef configASSERT',
    '#undef configASSERT',
    '#endif',
    '#define configASSERT(x)  if (!(x)) { __asm volatile("bkpt #0"); }',
    '',
    'extern uint32_t SystemCoreClock;',
    '',
    '#endif /* FREERTOS_CONFIG_H */',
  ].join('\n');
}
